# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_elementos', models.IntegerField(default=2)),
                ('pos_actual', models.IntegerField(default=0)),
                ('tiempo_transicion', models.IntegerField(default=5)),
                ('es_automatico', models.BooleanField()),
                ('es_circular', models.BooleanField()),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField()),
                ('descripcion', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('titulo', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='carrusel',
            name='elementos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.Contenido'),
        ),
    ]
