# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=50)),
                ('current_position', models.IntegerField(blank=True, default=0)),
                ('timer', models.IntegerField(blank=True, default=3)),
                ('auto', models.BooleanField(default=False)),
                ('circular', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='content/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('carousel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.Carousel')),
            ],
        ),
        migrations.RemoveField(
            model_name='carrusel',
            name='elementos',
        ),
        migrations.DeleteModel(
            name='Carrusel',
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
