# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elem', models.CharField(max_length=200)),
                ('ident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginacion.List')),
            ],
        ),
    ]
